apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: <ECR_URI>:latest
        ports:
        - containerPort: 5000
